"use strict";
var import_subpath = require('./subpath/index.cjs');
var import_file = require('./file.cjs');
var import_alias = require('./alias/index.cjs');
var import_folder_import = require('./folder-import/index.cjs');
var import_extensions = require('./extensions/index.cjs');
var import_level1 = require('./nested/level1/index.cjs');
var import_windows_path_test = require('./windows-path-test.cjs');
var import_windows_simulation_test = require('./windows-simulation-test.cjs');
var import_backslash_detector = require('./backslash-detector.cjs');
console.log("=== Testing esbuild-fix-imports-plugin ===");
console.log("Original tests:");
console.log("- Subpath import:", import_subpath.test);
console.log("- JS file import:", import_file.test);
console.log("\nAlias tests:");
console.log("- Aliased import:", import_alias.aliasedImport);
console.log("\nFolder import tests:");
console.log("- Folder import:", import_folder_import.folderImport);
console.log("\nExtensions tests:");
console.log("- TSX component:", import_extensions.extensionsTest.tsxComponent);
console.log("- JSON data:", import_extensions.extensionsTest.jsonData);
console.log("- CSS styles:", import_extensions.extensionsTest.cssStyles);
console.log("\nNested module tests:");
console.log("- Deep nested export:", import_level1.deepNestedExport);
console.log("\n=== Windows Path Tests ===");
(0, import_windows_path_test.testWindowsPaths)();
(0, import_windows_simulation_test.simulateWindowsPathHandling)();
(0, import_backslash_detector.detectBackslashes)();
console.log("\n=== All tests completed ===");
