import { test } from "./subpath/index.mjs";
import { test as jsTest } from "./file.mjs";
import { aliasedImport } from "./alias/index.mjs";
import { folderImport } from "./folder-import/index.mjs";
import { extensionsTest } from "./extensions/index.mjs";
import { deepNestedExport } from "./nested/level1/index.mjs";
import { testWindowsPaths } from "./windows-path-test.mjs";
import { simulateWindowsPathHandling } from "./windows-simulation-test.mjs";
import { detectBackslashes } from "./backslash-detector.mjs";
console.log("=== Testing esbuild-fix-imports-plugin ===");
console.log("Original tests:");
console.log("- Subpath import:", test);
console.log("- JS file import:", jsTest);
console.log("\nAlias tests:");
console.log("- Aliased import:", aliasedImport);
console.log("\nFolder import tests:");
console.log("- Folder import:", folderImport);
console.log("\nExtensions tests:");
console.log("- TSX component:", extensionsTest.tsxComponent);
console.log("- JSON data:", extensionsTest.jsonData);
console.log("- CSS styles:", extensionsTest.cssStyles);
console.log("\nNested module tests:");
console.log("- Deep nested export:", deepNestedExport);
console.log("\n=== Windows Path Tests ===");
testWindowsPaths();
simulateWindowsPathHandling();
detectBackslashes();
console.log("\n=== All tests completed ===");
//# sourceMappingURL=index.mjs.map